# Generated by Django 5.1.4 on 2026-04-08 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('rank', models.PositiveSmallIntegerField(verbose_name='Разряд')),
                ('hire_date', models.DateField(verbose_name='Дата приёма на работу')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('max_hours_per_week', models.PositiveSmallIntegerField(default=40, verbose_name='Макс. часов в неделю')),
                ('preferred_shift_type', models.CharField(choices=[('DAY', 'Дневная'), ('EVENING', 'Вечерняя'), ('NIGHT', 'Ночная'), ('ANY', 'Любая')], default='ANY', max_length=10, verbose_name='Предпочитаемая смена')),
                ('role', models.CharField(choices=[('ADMIN', 'Администратор'), ('EMPLOYEE', 'Сотрудник'), ('HR', 'Кадровик')], default='EMPLOYEE', max_length=10, verbose_name='Роль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('skills', models.ManyToManyField(blank=True, related_name='employees', to='scheduler.skill', verbose_name='Навыки')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('shift_type', models.CharField(choices=[('DAY', 'Дневная'), ('EVENING', 'Вечерняя'), ('NIGHT', 'Ночная')], max_length=10, verbose_name='Тип смены')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('required_employees', models.PositiveSmallIntegerField(default=1, verbose_name='Требуется сотрудников')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Место')),
                ('required_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='scheduler.skill', verbose_name='Требуемый навык')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('reason', models.CharField(max_length=200, verbose_name='Причина')),
                ('status', models.CharField(choices=[('PENDING', 'На рассмотрении'), ('APPROVED', 'Одобрено'), ('REJECTED', 'Отклонено')], default='PENDING', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_offs', to='scheduler.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Отгул/больничный',
                'verbose_name_plural': 'Отгулы и больничные',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PLANNED', 'Запланировано'), ('CONFIRMED', 'Подтверждено'), ('COMPLETED', 'Выполнено'), ('MISSED', 'Пропущено')], default='PLANNED', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='scheduler.employee', verbose_name='Сотрудник')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='scheduler.shift', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Назначение',
                'verbose_name_plural': 'Назначения',
                'ordering': ['-created_at'],
                'unique_together': {('shift', 'employee')},
            },
        ),
    ]
