# Generated by Django 5.1.4 on 2026-04-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='prefers_weekend_off',
            field=models.BooleanField(default=False, help_text='Мягкое ограничение: система будет стараться не ставить на выходные', verbose_name='Предпочитает выходные в сб–вс'),
        ),
    ]
